all:
	g++ -std=c++11 -Wall -Wno-stringop-truncation src/dNdy_y.cpp -o dNdy_y.exe -O3 -lgsl -lgslcblas -fno-stack-protector
	g++ -std=c++11 -Wall -Wno-stringop-truncation src/dNdQdy_Q.cpp -o dNdQdy_Q.exe -O3 -lgsl -lgslcblas -fno-stack-protector
	g++ -std=c++11 -Wall -Wno-stringop-truncation src/dNdqTdy_qT.cpp -o dNdqTdy_qT.exe -O3 -lgsl -lgslcblas -fno-stack-protector
