all:
	g++ -std=c++11 -Wall -Wno-stringop-truncation src/dCharmdy_y/dNdy_y_gg.cpp -o dNdy_y_gg.exe -O3 -lgsl -lgslcblas -fno-stack-protector
	g++ -std=c++11 -Wall -Wno-stringop-truncation src/dCharmdy_y/dNdy_y_qq.cpp -o dNdy_y_qq.exe -O3 -lgsl -lgslcblas -fno-stack-protector


	g++ -std=c++11 -Wall -Wno-stringop-truncation src/dCharmdQdy_Q/dNdQdy_Q_gg.cpp -o dNdQdy_Q_gg.exe -O3 -lgsl -lgslcblas -fno-stack-protector
	g++ -std=c++11 -Wall -Wno-stringop-truncation src/dCharmdQdy_Q/dNdQdy_Q_qq.cpp -o dNdQdy_Q_qq.exe -O3 -lgsl -lgslcblas -fno-stack-protector
	
	
	g++ -std=c++11 -Wall -Wno-stringop-truncation src/dCharmdqTdy_qT/dNdqTdy_qT_gg.cpp -o dNdqTdy_qT_gg.exe -O3 -lgsl -lgslcblas -fno-stack-protector
	g++ -std=c++11 -Wall -Wno-stringop-truncation src/dCharmdqTdy_qT/dNdqTdy_qT_qq.cpp -o dNdqTdy_qT_qq.exe -O3 -lgsl -lgslcblas -fno-stack-protector
	

	g++ -std=c++11 -Wall -Wno-stringop-truncation src/dCharmdtaudy_tau/dNdtaudy_tau_gg_not_integrated.cpp -o dNdtaudy_tau_gg_not_integrated_.exe -O3 -lgsl -lgslcblas -fno-stack-protector
	g++ -std=c++11 -Wall -Wno-stringop-truncation src/dCharmdtaudy_tau/dNdy_tau_gg.cpp -o dNdy_tau_gg.exe -O3 -lgsl -lgslcblas -fno-stack-protector
	
	g++ -std=c++11 -Wall -Wno-stringop-truncation src/Distribution_Temperaure_Energydensity/distribution.cpp -o distribution.exe -O3 -lgsl -lgslcblas -fno-stack-protector
