all:
	g++ -std=c++11 -Wall -Wno-stringop-truncation src/dNdy_y_gg.cpp -o dNdy_y_gg.exe -O3 -lgsl -lgslcblas -fno-stack-protector
	g++ -std=c++11 -Wall -Wno-stringop-truncation src/dNdy_y_qq.cpp -o dNdy_y_qq.exe -O3 -lgsl -lgslcblas -fno-stack-protector

