all:
	g++ -std=c++11 -Wall -Wno-stringop-truncation src/Main.cpp -o Calculate.exe -O3 -lgsl -lgslcblas -fno-stack-protector
	g++ -std=c++11 -Wall -Wno-stringop-truncation src/dNdtaudy_tau_gg_not_integrated.cpp -o dNdtaudy_tau_gg_not_integrated.exe -O3 -lgsl -lgslcblas -fno-stack-protector
